export const Users = [
    {
      id:1,
      profilePicture: "https://m.media-amazon.com/images/M/MV5BZGRlZTczNjktZDIwYS00YmFjLWE4MmQtMjU4N2ZmMDNkNTU4XkEyXkFqcGdeQXVyODAzNzAwOTU@._V1_.jpg",
      username: "Shayam Tripathi",
    },
    {
      id:2,
      profilePicture: "https://pbs.twimg.com/profile_images/1342669993004003338/j2TBg_XV_400x400.jpg",
      username: "Kachra Seth",
    },
    {
      id:3,
      profilePicture: "http://image3.mouthshut.com/images/MoviesMusic/photo/Hera-Pheri--2000--43741_24291.jpg",
      username: "Baburao Ganpatrao Apte",
    },
    {
      id:4,
      profilePicture: "assets/person/4.jpeg",
      username: "Rajan Sharma",
    },
    {
      id:5,
      profilePicture: "assets/person/5.jpeg",
      username: "Shyamal Das Chanchad",
    },
    {
      id:6,
      profilePicture: "assets/person/6.jpeg",
      username: "Raman Raja",
    },
    {
      id:7,
      profilePicture: "assets/person/7.jpeg",
      username: "Ranchod Das",
    },
    {
      id:8,
      profilePicture: "assets/person/8.jpeg",
      username: "Rajveer",
    },
    {
      id:9,
      profilePicture: "https://i2.cinestaan.com/image-bank/1500-1500/61001-62000/61305.jpg",
      username: "Dinesh",
    },
    {
      id:10,
      profilePicture: "https://i2.cinestaan.com/image-bank/1500-1500/61001-62000/61305.jpg",
      username: "Rahul Sinha",
    },
  ];
  
  export const Posts = [
    {
      id: 1,
      desc: "Love For All, Hatred For None.",
      photo: "assets/post/1.jpeg",
      date: "5 mins ago",
      userId: 1,
      like: 32,
      comment: 9,
    },
    {
      id: 2,
      photo: "assets/post/2.jpeg",
      date: "15 mins ago",
      userId: 2,
      like: 2,
      comment: 1,
    },
    {
      id: 3,
      desc: "Every moment is a fresh beginning.",
      photo: "assets/post/3.jpeg",
      date: "1 hour ago",
      userId: 3,
      like: 61,
      comment: 2,
    },
    {
      id: 4,
      photo: "assets/post/4.jpeg",
      date: "4 hours ago",
      userId: 4,
      like: 7,
      comment: 3,
    },
    {
      id: 5,
      photo: "assets/post/5.jpeg",
      date: "5 hours ago",
      userId: 5,
      like: 23,
      comment: 5,
    },
    {
      id: 6,
      photo: "assets/post/6.jpeg",
      date: "1 day ago",
      userId: 6,
      like: 44,
      comment: 6,
    },
    {
      id: 7,
      desc: "Never regret anything that made you smile.",
      photo: "assets/post/7.jpeg",
      date: "2 days ago",
      userId: 7,
      like: 52,
      comment: 3,
    },
    {
      id: 8,
      photo: "assets/post/8.jpeg",
      date: "3 days ago",
      userId: 8,
      like: 15,
      comment: 1,
    },
    {
      id: 9,
      desc: "Change the world by being yourself.",
      photo: "assets/post/9.jpeg",
      date: "5 days ago",
      userId: 9,
      like: 11,
      comment: 2,
    },
    {
      id: 10,
      photo: "assets/post/10.jpeg",
      date: "1 week ago",
      userId: 10,
      like: 104,
      comment: 12,
    },
  ];